name: Build PDF from Typst

on:
  push:
    branches:
      - master
    # paths:
    #   - 'lecture-notes/*.typ'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name:  setup fontist
      #   uses: fontist/setup@v2

      # - name: install font
      #   run: |
      #     fontist update
      #     fontist install "Fira Code"
      #     fontist install "Open Sans"

      - name: Install pdf2svg
        run: |
          sudo apt-get update
          sudo apt-get install -y pdf2svg fonts-cmu

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Build PDF from Typst sources
        run: |
          typst compile lecture-notes/Lecture-notes.typ Signals-and-systems-m1-tpe.pdf  --font-path /usr/share/fonts
          typst compile  --input solutions=false TDs/TD2.typ TD2.pdf  --font-path /usr/share/fonts
          typst compile  --input solutions=true TDs/TD2.typ TD2-correction.pdf --font-path /usr/share/fonts
          typst compile  --input solutions=false TDs/TD3.typ TD3.pdf  --font-path /usr/share/fonts
          typst compile  --input solutions=true TDs/TD3.typ TD3-correction.pdf --font-path /usr/share/fonts
          typst compile  --input solutions=false TDs/TD4.typ TD4.pdf  --font-path /usr/share/fonts
          typst compile  --input solutions=true TDs/TD4.typ TD4-correction.pdf --font-path /usr/share/fonts

      - name: Convert first page from PDF to SVG
        run: |
          pdf2svg Signals-and-systems-m1-tpe.pdf Signals-and-systems-m1-tpe.svg
          mkdir output
          mv *{.svg,.pdf} output/.

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          force_orphan: true
